### ISSUE TITLE
用scollerview会崩溃

### ISSUE THREAD

**Issue by Demonsword27** [chennyhuang/HZPhotoBrowser#11]
就是一个demo  在scollerview 上加一些照片 
UIImageView \* view =  sender.view;
    HZPhotoBrowser *browserVc = [[HZPhotoBrowser alloc] init];
    browserVc.sourceImagesContainerView = ScrollView;
    browserVc.imageCount = _srcStringArray.count;
    browserVc.currentImageIndex = view.tag;
    // 代理
    browserVc.delegate = self;
    // 展示图片浏览器
    [browserVc show];

会崩溃 不太懂啊

**Comment by chennyhuang** [comment]
已经完全改版
