### ISSUE TITLE
Warning: Attempt to present <HZPhotoBrowser: 0x113d415d0> on <FOXNavigationViewController: 0x114817000> whose view is not in the window hierarchy!

### ISSUE THREAD

**Issue by lianxingbo** [chennyhuang/HZPhotoBrowser#15]
Warning: Attempt to present <HZPhotoBrowser: 0x113d415d0> on <FOXNavigationViewController: 0x114817000> whose view is not in the window hierarchy!

点击show之后不弹出

**Comment by chennyhuang** [comment]
已经完全改版
