### ISSUE TITLE
能加个好友吗

### ISSUE THREAD

**Issue by godlikezjy** [chennyhuang/HZPhotoBrowser#21]
很喜欢你写的demo，想请教几个问题，179434316

**Comment by godlikezjy** [comment]
179434316




| |
i am a 程序猿；
邮箱：13269734777@163.com
|

签名由 网易邮箱大师 定制

在2018年07月15日 13:18，chennyhuang 写道：

Closed #21.

**Comment by MuyiXiaotian** [comment]
有个问题求指教
