### ISSUE TITLE
一点问题

### ISSUE THREAD

**Issue by developforapple** [chennyhuang/HZPhotoBrowser#3]
convertToRect 有时候得不到想要的结果。建议在viewDidLoad里事先把所有sourceView的rect计算出来。

**Comment by chennyhuang** [comment]
有问题多数因为你直接用了 UITableviewController，从而导致convertRect转换出来的rect不准确。建议用UIViewController然后在上面添加tableview来布局。

**Comment by shanbozhu** [comment]
您好,我用UIViewController在上面添加tableview来布局的,但是仍旧会出现切换动画时位置不正确的问题.

**Comment by zuolingfeng** [comment]
我也出现了用tableview布局，动画错位的问题

**Comment by invokerclk** [comment]
同样出现动画错位 如何解决

**Comment by chennyhuang** [comment]
建议用 https://github.com/chennyhuang/ptoto 这个工程，这里面已解决动画错位问题

**Comment by wangguanyang** [comment]
![img_4425](https://cloud.githubusercontent.com/assets/14039723/17992848/600ef9d0-6b7d-11e6-9c3c-e53fab968836.PNG)
第一次加载出错,点击好几次才加载出来图片,你看看是咋回事.

**Comment by chennyhuang** [comment]
![http](https://cloud.githubusercontent.com/assets/8370852/17993214/7b89e8f2-6b80-11e6-8fd2-0675571ed421.png)

**Comment by wangguanyang** [comment]
@chennyhuang 我是设置了这个选项的,是不是其他原因呢?

**Comment by chennyhuang** [comment]
重新下载我的工程再试试，可能是你网络不好，只能帮你到这
