### ISSUE TITLE
点击奔溃

### ISSUE THREAD

**Issue by tukzi** [chennyhuang/HZPhotoBrowser#5]
如果你指定的父视图里面的subviews 不仅仅包含 图片 而且 包括 其他视图 比如 UILabel，UIbutton，UIimageView 啊，然后你用这个去取 UIView *sourceView = self.sourceImagesContainerView.subviews[self.currentImageIndex]; 得到的sourceView 就不能保证是点击的图片，有可能取出来的是UIlabel什么的然后就挂了

**Comment by chennyhuang** [comment]
现实情况就只能是图片，其他的形式需要你自己去修改

**Comment by tukzi** [comment]
看了一下好像不太好扩展的样子，如果父视图里面只能放图片，那么使用范围就就比较小了，实际项目就算cell里面也不可能只有图片这一个控件吧，呵呵
